language: go
go: 1.7
install:
  - go get -v github.com/Masterminds/glide
  - cd $GOPATH/src/github.com/Masterminds/glide && go install && cd -
script: make test
sudo: false
go_import_path: github.com/CopperMantis/CopperMantis
